name: test_giphy_app
description: "Example gifs app demonstrating basic coding and architectural skills."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  dio: ^5.9.0
  retrofit: ^4.9.0
  json_annotation: ^4.9.0
  logger: ^2.6.2

  auto_route: ^10.2.1
  get_it: ^8.3.0
  injectable: ^2.6.0

  async: ^2.13.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1

  infinite_scroll_pagination: ^4.1.0
  shimmer_animation: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.0

  flutter_lints: ^6.0.0

  build_runner: ^2.10.3

  auto_route_generator: ^10.2.6
  injectable_generator: ^2.9.1
  json_serializable: ^6.8.0
  retrofit_generator: ^10.1.4

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi/Satoshi-Regular.otf
        - asset: fonts/Satoshi/Satoshi-Italic.otf
          style: italic
        - asset: fonts/Satoshi/Satoshi-Bold.otf
          weight: 700
        - asset: fonts/Satoshi/Satoshi-BoldItalic.otf
          weight: 700
          style: italic
